In [59]:
import pandas as pd

In [3]:
orders = pd.read_table('http://bit.ly/chiporders')

In [34]:
user_cols = ['userid','age','gender','occupation','zipcode']
movies = pd.read_table('http://bit.ly/movieusers',sep='|', header=None, names=user_cols)

In [99]:
ufo = pd.read_csv('http://bit.ly/uforeports')

In [105]:
ufo.columns

Index(['city', 'colors_reported', 'shape_reported', 'state', 'time'], dtype='object')

In [104]:
ufo.columns = ufo.columns.str.replace(' ','_')

In [93]:
ufo.rename(columns={'Colors Reported':'Colors_Reported', 'Shape Reported':'Shape_Reported'},inplace=True)

In [97]:
ufo_cols = ['city','colors reported', 'shape reported','state','time']
ufo.columns = ufo_cols

In [102]:
ufo.head()

                   city colors reported shape reported state             time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [101]:
ufo = pd.read_csv('http://bit.ly/uforeports', names=ufo_cols, header=0)

In [135]:
movies = pd.read_csv('http://bit.ly/imdbratings')

In [110]:
movies.columns = movies.columns.str.replace('_','')

In [123]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [134]:
movies.sort_values(['duration','title'],ascending=True)

,star_rating,title,content_rating,genre,duration,actors_list
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
338,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"[u'Werner Krauss', u'Conrad Veidt', u'Friedric..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
88,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
742,7.6,Following,R,Mystery,69,"[u'Jeremy Theobald', u'Alex Haw', u'Lucy Russe..."
351,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']"
938,7.4,Alice in Wonderland,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
303,8.0,The Nightmare Before Christmas,PG,Animation,76,"[u'Danny Elfman', u'Chris Sarandon', u""Catheri..."
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
489,7.8,The Triplets of Belleville,PG-13,Animation,78,"[u'Mich\xe8le Caucheteux', u'Jean-Claude Donda..."
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
535,7.8,Zelig,PG,Comedy,79,"[u'Woody Allen', u'Mia Farrow', u'Patrick Horg..."
283,8.1,Before Sunset,R,Drama,80,"[u'Ethan Hawke', u'Julie Delpy', u'Vernon Dobt..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
853,7.5,L'illusionniste,PG,Animation,80,"[u'Jean-Claude Donda', u'Eilidh Rankin', u'Dun..."
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
533,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
622,7.7,The Dinner Game,PG-13,Comedy,80,"[u'Thierry Lhermitte', u'Jacques Villeret', u'..."
738,7.6,Army of Darkness,R,Comedy,81,"[u'Bruce Campbell', u'Embeth Davidtz', u'Marcu..."
789,7.6,Ice Age,PG,Animation,81,"[u'Denis Leary', u'John Leguizamo', u'Ray Roma..."
330,8.0,Nosferatu,UNRATED,Horror,81,"[u'Max Schreck', u'Greta Schr\xf6der', u'Ruth ..."
541,7.8,South Park: Bigger Longer & Uncut,R,Animation,81,"[u'Trey Parker', u'Matt Stone', u'Mary Kay Ber..."
117,8.3,Toy Story,G,Animation,81,"[u'Tom Hanks', u'Tim Allen', u'Don Rickles']"
595,7.7,The Purple Rose of Cairo,PG,Comedy,82,"[u'Mia Farrow', u'Jeff Daniels', u'Danny Aiello']"
306,8.0,This Is Spinal Tap,R,Comedy,82,"[u'Rob Reiner', u'Michael McKean', u'Christoph..."
343,8.0,Ghost in the Shell,NOT RATED,Animation,83,"[u'Atsuko Tanaka', u'Iemasa Kayumi', u'Akio \x..."
174,8.2,Persona,NOT RATED,Drama,83,"[u'Bibi Andersson', u'Liv Ullmann', u'Margaret..."
759,7.6,Robin Hood,G,Animation,83,"[u'Brian Bedford', u'Phil Harris', u'Roger Mil..."
...,...,...,...,...,...,...
361,8.0,Fiddler on the Roof,G,Drama,181,"[u'Topol', u'Norma Crane', u'Leonard Frey']"
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
245,8.1,Barry Lyndon,PG,Adventure,184,"[u""Ryan O'Neal"", u'Marisa Berenson', u'Patrick..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
611,7.7,Short Cuts,R,Comedy,187,"[u'Andie MacDowell', u'Julianne Moore', u'Tim ..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
318,8.0,Magnolia,R,Drama,188,"[u'Tom Cruise', u'Jason Robards', u'Julianne M..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
220,8.1,Gandhi,PG,Biography,191,"[u'Ben Kingsley', u'John Gielgud', u'Candice B..."
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."
424,7.9,The Right Stuff,R,Adventure,193,"[u'Sam Shepard', u'Scott Glenn', u'Ed Harris']"
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
335,8.0,Doctor Zhivago,PG-13,Drama,197,"[u'Omar Sharif', u'Julie Christie', u'Geraldin..."
385,8.0,Spartacus,PG-13,Action,197,"[u'Kirk Douglas', u'Laurence Olivier', u'Jean ..."
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [136]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [146]:
is_long = pd.Series([x >= 200 for x in movies.duration])
movies[is_long]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [175]:
movies[(movies.duration >= 200) & (movies.genre.isin(['Crime','Drama']))]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [178]:
ufo = pd.read_csv('http://bit.ly/uforeports', usecols=['City','State'], nrows=3)

In [179]:
ufo.head()

          City State
0       Ithaca    NY
1  Willingboro    NJ
2      Holyoke    CO

In [189]:
for index, row in ufo.iterrows():
    print (index, row.City, row.State)

0 Ithaca NY
1 Willingboro NJ
2 Holyoke CO

In [118]:
ufo.drop(['City','State'],axis=1, inplace=True)

In [120]:
ufo.drop([0,1],axis=0,inplace=True)

In [121]:
ufo.head()

  Shape Reported             Time
2           OVAL  2/15/1931 14:00
3           DISK   6/1/1931 13:00
4          LIGHT  4/18/1933 19:00
5           DISK  9/15/1934 15:30
6         CIRCLE   6/15/1935 0:00

In [193]:
drinks = pd.read_csv('http://bit.ly/drinksbycountry')

In [200]:
import numpy as np
drinks.select_dtypes(include=[np.number]).dtypes

beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
dtype: object

In [210]:
drinks.describe(exclude=['object'])

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
count,193.000000,193.000000,193.000000,193.000000
mean,106.160622,80.994819,49.450777,4.717098
std,101.143103,88.284312,79.697598,3.773298
min,0.000000,0.000000,0.000000,0.000000
25%,20.000000,4.000000,1.000000,1.300000
50%,76.000000,56.000000,8.000000,4.200000
75%,188.000000,128.000000,59.000000,7.200000
max,376.000000,438.000000,370.000000,14.400000